"""Published 2026 holiday shifts, transcribed from the county page."""

from __future__ import annotations

from datetime import date

import pytest

from pgpickup.engine import resolve_service_date
from pgpickup.holidays import load_holiday_table

TABLE = load_holiday_table()

# Nominal regular day -> service day. Copied from the dated tables on
# https://www.princegeorgescountymd.gov/departments-offices/environment/waste-recycling/holiday-waste-collection-schedule
# checked 2026-10-06. Not generated by the engine.
PUBLISHED = [
    # New Year's Day, Thursday 2026-01-01. Monday–Wednesday stay; Thu/Fri slide.
    (date(2025, 12, 29), date(2025, 12, 29)),
    (date(2025, 12, 30), date(2025, 12, 30)),
    (date(2025, 12, 31), date(2025, 12, 31)),
    (date(2026, 1, 1), date(2026, 1, 2)),
    (date(2026, 1, 2), date(2026, 1, 3)),
    # Martin Luther King, Jr. Day, Monday 2026-01-19. Whole week slides.
    (date(2026, 1, 19), date(2026, 1, 20)),
    (date(2026, 1, 20), date(2026, 1, 21)),
    (date(2026, 1, 21), date(2026, 1, 22)),
    (date(2026, 1, 22), date(2026, 1, 23)),
    (date(2026, 1, 23), date(2026, 1, 24)),
    # Presidents' Day, Monday 2026-02-16. Collection runs.
    (date(2026, 2, 16), date(2026, 2, 16)),
    (date(2026, 2, 17), date(2026, 2, 17)),
    (date(2026, 2, 18), date(2026, 2, 18)),
    (date(2026, 2, 19), date(2026, 2, 19)),
    (date(2026, 2, 20), date(2026, 2, 20)),
    # Memorial Day, Monday 2026-05-25.
    (date(2026, 5, 25), date(2026, 5, 26)),
    (date(2026, 5, 26), date(2026, 5, 27)),
    (date(2026, 5, 27), date(2026, 5, 28)),
    (date(2026, 5, 28), date(2026, 5, 29)),
    (date(2026, 5, 29), date(2026, 5, 30)),
    # Juneteenth, Friday 2026-06-19. Only Friday moves.
    (date(2026, 6, 15), date(2026, 6, 15)),
    (date(2026, 6, 16), date(2026, 6, 16)),
    (date(2026, 6, 17), date(2026, 6, 17)),
    (date(2026, 6, 18), date(2026, 6, 18)),
    (date(2026, 6, 19), date(2026, 6, 20)),
    # Independence Day, Saturday 2026-07-04. Dated table: no weekday change.
    (date(2026, 6, 29), date(2026, 6, 29)),
    (date(2026, 6, 30), date(2026, 6, 30)),
    (date(2026, 7, 1), date(2026, 7, 1)),
    (date(2026, 7, 2), date(2026, 7, 2)),
    (date(2026, 7, 3), date(2026, 7, 3)),
    # Labor Day, Monday 2026-09-07.
    (date(2026, 9, 7), date(2026, 9, 8)),
    (date(2026, 9, 8), date(2026, 9, 9)),
    (date(2026, 9, 9), date(2026, 9, 10)),
    (date(2026, 9, 10), date(2026, 9, 11)),
    (date(2026, 9, 11), date(2026, 9, 12)),
    # Native American Day, Monday 2026-10-12. Collection runs.
    (date(2026, 10, 12), date(2026, 10, 12)),
    (date(2026, 10, 13), date(2026, 10, 13)),
    (date(2026, 10, 14), date(2026, 10, 14)),
    (date(2026, 10, 15), date(2026, 10, 15)),
    (date(2026, 10, 16), date(2026, 10, 16)),
    # Veterans Day, Wednesday 2026-11-11. Collection runs.
    (date(2026, 11, 9), date(2026, 11, 9)),
    (date(2026, 11, 10), date(2026, 11, 10)),
    (date(2026, 11, 11), date(2026, 11, 11)),
    (date(2026, 11, 12), date(2026, 11, 12)),
    (date(2026, 11, 13), date(2026, 11, 13)),
    # Thanksgiving, Thursday 2026-11-26 (page heading misstates the date).
    (date(2026, 11, 23), date(2026, 11, 23)),
    (date(2026, 11, 24), date(2026, 11, 24)),
    (date(2026, 11, 25), date(2026, 11, 25)),
    (date(2026, 11, 26), date(2026, 11, 27)),
    (date(2026, 11, 27), date(2026, 11, 28)),
    # Christmas, Friday 2026-12-25. Only Friday moves.
    (date(2026, 12, 21), date(2026, 12, 21)),
    (date(2026, 12, 22), date(2026, 12, 22)),
    (date(2026, 12, 23), date(2026, 12, 23)),
    (date(2026, 12, 24), date(2026, 12, 24)),
    (date(2026, 12, 25), date(2026, 12, 26)),
    # New Year's Day 2027, Friday 2027-01-01. Only published 2027 row.
    (date(2026, 12, 28), date(2026, 12, 28)),
    (date(2026, 12, 29), date(2026, 12, 29)),
    (date(2026, 12, 30), date(2026, 12, 30)),
    (date(2026, 12, 31), date(2026, 12, 31)),
    (date(2027, 1, 1), date(2027, 1, 2)),
]

SLIDE_DATES = {
    date(2026, 1, 1),
    date(2026, 1, 19),
    date(2026, 5, 25),
    date(2026, 6, 19),
    date(2026, 9, 7),
    date(2026, 11, 26),
    date(2026, 12, 25),
    date(2027, 1, 1),
}
OPEN_DATES = {
    date(2026, 2, 16),
    date(2026, 7, 4),
    date(2026, 10, 12),
    date(2026, 11, 11),
}


def test_table_matches_the_published_set():
    assert {holiday.date for holiday in TABLE.holidays} == SLIDE_DATES | OPEN_DATES
    assert {holiday.date for holiday in TABLE.holidays if holiday.observe == "slide"} == SLIDE_DATES
    assert {holiday.date for holiday in TABLE.holidays if holiday.observe == "none"} == OPEN_DATES
    assert TABLE.checked == date(2026, 10, 6)
    assert "holiday-waste-collection-schedule" in TABLE.source_url


@pytest.mark.parametrize(("nominal", "expected"), PUBLISHED)
def test_published_shift(nominal: date, expected: date):
    service, name = resolve_service_date(nominal, TABLE.holidays, "trash")
    assert service == expected
    assert (service != nominal) == (name is not None)


@pytest.mark.parametrize("stream", ["trash", "recycling", "yard_waste", "bulky"])
def test_mlk_slides_every_stream(stream: str):
    service, name = resolve_service_date(date(2026, 1, 19), TABLE.holidays, stream)
    assert service == date(2026, 1, 20)
    assert name == "Martin Luther King, Jr. Day"


def test_shift_names_for_new_year_and_presidents_day():
    service, name = resolve_service_date(date(2026, 1, 1), TABLE.holidays, "recycling")
    assert service == date(2026, 1, 2)
    assert name == "New Year's Day"
    service, name = resolve_service_date(date(2026, 2, 16), TABLE.holidays, "yard_waste")
    assert service == date(2026, 2, 16)
    assert name is None


def test_ordinary_thursday_does_not_move():
    service, name = resolve_service_date(date(2026, 3, 5), TABLE.holidays, "trash")
    assert service == date(2026, 3, 5)
    assert name is None
